
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CHAR DOUBLE FLOAT ID INT SEMICOLONstatement : ID ASSIGN expression SEMICOLON\n                 | ID SEMICOLONexpression : INT\n                  | FLOAT\n                  | DOUBLE\n                  | CHAR\n                  | ID'
    
_lr_action_items = {'ID':([0,3,],[2,5,]),'$end':([1,4,11,],[0,-2,-1,]),'ASSIGN':([2,],[3,]),'SEMICOLON':([2,5,6,7,8,9,10,],[4,-7,11,-3,-4,-5,-6,]),'INT':([3,],[7,]),'FLOAT':([3,],[8,]),'DOUBLE':([3,],[9,]),'CHAR':([3,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID ASSIGN expression SEMICOLON','statement',4,'p_statement','typeMismatch.py',54),
  ('statement -> ID SEMICOLON','statement',2,'p_statement','typeMismatch.py',55),
  ('expression -> INT','expression',1,'p_expression','typeMismatch.py',59),
  ('expression -> FLOAT','expression',1,'p_expression','typeMismatch.py',60),
  ('expression -> DOUBLE','expression',1,'p_expression','typeMismatch.py',61),
  ('expression -> CHAR','expression',1,'p_expression','typeMismatch.py',62),
  ('expression -> ID','expression',1,'p_expression','typeMismatch.py',63),
]
